{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentguard.fullname" . }}-secret
  labels:
    {{- include "agentguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  AGENTGUARD_API_KEY: {{ .Values.secrets.agentguardApiKey | quote }}
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | quote }}
{{- end }}
